name: build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  COMPILER: VS_143
  COMPILER_FRIENDLY: vs2022
  GENERATOR: "Visual Studio 17 2022"
  CMAKE_COMMAND: cmake
  CMAKE_OPTION_LIBS: "-DARCHITECTURE=Win32"
  CMAKE_OPTION_GENERATE: "-A Win32"
  CMAKE_OPTION_BUILD: "--config Release"
  BUILD_DIR: build
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: build script
        run: ci_scripts\build_local_appveyor_vs2019.bat
        shell: cmd

